// This script is auto-generated by UINodeEditor, which is a tool given by PurpleFlowerCore
// Please do not modify this script manually
// url: https://github.com/Pditine/PurpleFlowerCore

using UnityEngine;
using UnityEngine.UI;
namespace UI
{
    public partial class ScoreUI
    {
        [SerializeField] private Text ScoreUIText;
        protected override void InitEvent()
        {

        }
    }
}